from __future__ import annotations
from ..data import User, Guild, GuildChannel
from typing import Optional

class DefaultCache:
	def __init__(self):
		pass

	async def cache_user(self, user: User): ...
	async def cache_guild(self, user: Guild): ...

	def get_user(self, id: int) -> Optional[User]: ...
	def get_guild(self, id: int) -> Optional[Guild]: ...
	def get_channel(self, id: int) -> Optional[GuildChannel]: ...

	async def fetch_guild(self, id: int) -> Optional[Guild]: ...
